language: csharp
sudo: true
mono: none
dist: xenial
dotnet: 2.2.203
os:
  - linux
  - osx
branches:
  only:
    - master
script:
  - dotnet restore
  - dotnet build -c Release
  - dotnet test -c Release -v n
#deploy:
#  skip_cleanup: true
#  provider: script
#  script: dotnet nuget push ${TRAVIS_BUILD_DIR}/**/*.nupkg -k ${NUGET_API_KEY}
#  on:
#    branch: master
#    os: linux
